import { Router } from 'express';
import { getHealth } from '../controllers/healthController.js';
import authRoutes from './authRoutes.js';
import appointmentRoutes from './appointmentRoutes.js';
import departmentRoutes from './departmentRoutes.js';
import statsRoutes from './statsRoutes.js';
import userRoutes from './userRoutes.js';
import prescriptionRoutes from './prescriptionRoutes.js';
import doctorRoutes from './doctorRoutes.js';
import doctorProfileRoutes from './doctorProfileRoutes.js';
import doctorPharmacyRoutes from './doctorPharmacyRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import doctorSettingsRoutes from './doctorSettingsRoutes.js';
import patientRoutes from './patientRoutes.js';
import patientProfileRoutes from './patientProfileRoutes.js';
import patientPasswordRoutes from './patientPasswordRoutes.js';
import patientSummaryRoutes from './patientSummaryRoutes.js';
import patientReportRoutes from './patientReportRoutes.js';
import patientPrescriptionRoutes from './patientPrescriptionRoutes.js';
import patientBillingRoutes from './patientBillingRoutes.js';
import patientExportRoutes from './patientExportRoutes.js';
import adminProfileRoutes from './adminProfileRoutes.js';
import adminSecurityRoutes from './adminSecurityRoutes.js';
import systemSettingsRoutes from './systemSettingsRoutes.js';
import adminSummaryRoutes from './adminSummaryRoutes.js';
import adminFinancialRoutes from './adminFinancialRoutes.js';
import activityLogRoutes from './activityLogRoutes.js';
import adminNotificationRoutes from './adminNotificationRoutes.js';
import adminDataRoutes from './adminDataRoutes.js';
import adminSecurityStatusRoutes from './adminSecurityStatusRoutes.js';
import { adminLimiter } from '../middleware/adminLimiter.js';
import publicDoctorRoutes from './publicDoctorRoutes.js';
import adminPharmacyRoutes from './adminPharmacyRoutes.js';
import patientNotificationRoutes from './patientNotificationRoutes.js';

const router = Router();

router.get('/health', getHealth);
router.use('/auth', authRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/departments', departmentRoutes);
router.use('/stats', statsRoutes);
router.use('/users', userRoutes);
router.use('/prescriptions', prescriptionRoutes);
router.use('/doctors', doctorRoutes);
router.use('/doctor', doctorProfileRoutes);
router.use('/doctor', doctorPharmacyRoutes);
router.use('/doctor', notificationRoutes);
router.use('/doctor', doctorSettingsRoutes);
router.use('/patient', patientRoutes);
router.use('/patient', patientProfileRoutes);
router.use('/patient', patientPasswordRoutes);
router.use('/patient', patientSummaryRoutes);
router.use('/patient', patientReportRoutes);
router.use('/patient', patientPrescriptionRoutes);
router.use('/patient', patientBillingRoutes);
router.use('/patient', patientNotificationRoutes);
router.use('/patient', patientExportRoutes);
router.use('/public', publicDoctorRoutes);
router.use('/admin', adminLimiter, adminProfileRoutes);
router.use('/admin', adminLimiter, adminSecurityRoutes);
router.use('/admin', adminLimiter, systemSettingsRoutes);
router.use('/admin', adminLimiter, adminSummaryRoutes);
router.use('/admin', adminLimiter, adminFinancialRoutes);
router.use('/admin', adminLimiter, activityLogRoutes);
router.use('/admin', adminLimiter, adminNotificationRoutes);
router.use('/admin', adminLimiter, adminDataRoutes);
router.use('/admin', adminLimiter, adminSecurityStatusRoutes);
router.use('/admin', adminLimiter, adminPharmacyRoutes);

export default router;
